# Instrument configurations for the long-slit tutorial.
#   use_me:    Flag for inclusion (1) or exclusion (0) from processing
#   ObsType:   Observation type (DARK|FLAT|ARC|OBJECT)
#   ReadMode:  Readout mode (Bright|Medium|Dark')
#   Disperser: Name of grism in use
#   AperMask:  Name of slitmask in use
#   Filter:    Name of filter in use
#   Texp_flat: Exposure duration of flat-field
#   Texp_arc:  Exposure duration of Ar comparison lamp
#   Texp_sci:  Exposure duration of science target
#   Object:    Target name
#   DateObs:   Calendar date of observation
JH:
    ObsType:   OBJECT
    ReadMode:  Bright
    N_Reads:   1
    Disperser: 'JH_%'
    AperMask:  4pix-slit
    Filter:    'JH_%'
    CentWave:  1.4
    Texp_arc:  15
    Texp_flat: 4
    Texp_sci:  30
    MCbpm:     MCbpm_JH
    MCflat:    MCflat_JH
    Arc:       wAr_JH_061
    Object:    'J0126-5505%'
    DateObs:   '2014-01-16:2014-02-17'

HK:
    ObsType:   OBJECT
    ReadMode:  Bright
    N_Reads:   1
    Disperser: 'HK_%'
    AperMask:  4pix-slit
    Filter:    'HK_%'
    CentWave:  1.87
    Texp_arc:  40
    Texp_flat: 80
    Texp_sci:  30
    MCbpm:     MCbpm_HK
    MCflat:    MCflat_HK
    Arc:       wAr_HK_067
    Object:    'J0126-5505%'
    DateObs:   '2014-01-16:2014-02-17'
...